# -*- coding: utf-8 -*-
"""cmnt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HXws9Iyaa_6ZXTepN2iv51BFHvqhUklO
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
df=pd.read_csv('deep learning - deep learning.csv')
df.head()

from sklearn.svm import SVR
regressor=SVR(kernel='linear')

import matplotlib.pyplot as plt
plt.scatter(df['c_c_s'],df['cmnt'])

from sklearn.model_selection import train_test_split

X = df[['c_c_s',
 'b_f_s_prcnt',
 'f_a_prcnt',
 's_plast_prcnt',
 'w_c_r',
 'co_agg_prcnt',
 'fi_agg_prcnt']]
y = df['cmnt']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)

regressor.fit(X_train,y_train)
pred=regressor.predict(X_test)

print(regressor.score(X_test,y_test))
from sklearn.metrics import r2_score
print(r2_score(y_test,pred))