# -*- coding: utf-8 -*-
"""Copy of random forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SpSQQxepaL1XciF0Q5ZfbY6jYmJYWcYC
"""

from google.colab import files

uploaded = files.upload()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('lol.csv')
dataset

X = dataset[['c_c_s',
 'b_f_s_prcnt',
 'f_a_prcnt',
 's_plast_prcnt',
 'w_c_r',
 'co_agg_prcnt',
 'fi_agg_prcnt']]
y = dataset[['cmnt','wtr','fi_agg_prcnt',
 'co_agg']]

list(dataset.columns.values)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)

import matplotlib.pyplot as plt   #Data visualisation libraries
import seaborn as sns
# %matplotlib inline

sns.pairplot(dataset)

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 300, random_state = 0)
regressor.fit(X,y)

regressor.fit(X_train,y_train)
pred=regressor.predict(X_test)

print(regressor.score(X_test,y_test))
from sklearn.metrics import r2_score
print(r2_score(y_test,pred))

