# -*- coding: utf-8 -*-
"""Copy of elastic net.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11lRGhEUVtwz3nOo6kXGAsfBmy7s7GzYL
"""

from google.colab import files

uploaded = files.upload()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('lol.csv')
dataset

X = dataset[['c_c_s',
 'b_f_s_prcnt',
 'f_a_prcnt',
 's_plast_prcnt',
 'w_c_r',
 'co_agg_prcnt',
 'fi_agg_prcnt']]
y = dataset[['cmnt','wtr','fi_agg_prcnt',
 'co_agg']]

list(dataset.columns.values)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)

import matplotlib.pyplot as plt   #Data visualisation libraries
import seaborn as sns
# %matplotlib inline

from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression

X, y = make_regression(n_features=2, random_state=0)
regr = ElasticNet(random_state=0)
# regr.fit(X, y)

regr.fit(X_train,y_train)
pred=regr.predict(X_test)

print(regr.score(X_test,y_test))
from sklearn.metrics import r2_score
print(r2_score(y_test,pred))

