# -*- coding: utf-8 -*-
"""Decision tree regression .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VABBw3sGZZLtG-gr0XusVuISuds7wykv
"""

from google.colab import files

uploaded = files.upload()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('lol.csv')
dataset

X = dataset[['Blast Furnace Slag (%)',
 'Fly Ash (%)',
 'Superplasticizer (%)',
 'w/c ratio ',
 '% of coarse aggregate',
 '% of fine aggregate ', 'Concrete compressive strength(MPa, megapascals) ' ]]
y = dataset[['Coarse Aggregate  (kg in a m^3 mixture)',
 'Fine Aggregate (kg in a m^3 mixture)',
 'Water  (kg in a m^3 mixture)',
 'Cement (kg in a m^3 mixture)']]

list(dataset.columns.values)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X, y)

regressor.fit(X_train,y_train)
pred=regressor.predict(X_test)

print(regressor.score(X_test,y_test))
from sklearn.metrics import r2_score
print(r2_score(y_test,pred))

x = np.array([[20,0,0,0,0.40,60,40]])


regressor.predict(x)

